### ISSUE TITLE
Use a game specific index.html

### ISSUE THREAD

**Issue by DeaconDesperado** [joeyespo/py-impactjs#1]
Loving this server, as a python/flask guy myself this is perfect.

I am curious if you think it would be of benefit to have the endpoint for impact files look in the game directory for an `index.html` before serving the impact global one.  My use case includes adding other JS libs to the html markup, although I suppose one could load them from within the JS as well.  Thoughts?

**Comment by joeyespo** [comment]
Thanks!

I think that would be very cool! The only downside being, you probably don't want to include that index.html in your source control, since it's tool-dependent. It would be a good catch-all workaround. I'll take a pull request for it if you were thinking about implementing it.

As for adding JS libs, if these are for your Impact game--as opposed to using them to customize this tool--then yeah, your second suggestion is probably better. Do you think there's a way to add them from Impact directly?

**Comment by DeaconDesperado** [comment]
@joeyespo I'm going to try to put something together as a demo and will send it to you.

What I originally led me to the thought was the need to add more `<script>` tags to load other libs.  I was utilizing socket.io in my particular case.  Retrospectively, I'm actually just going to do the load calls in the JS code.  Still, it would be cool for the server to first assume that an index.html in a game specific directory was preferential for that individual game, and then default back to the py-impactjs included one if no file exists there.

The setup I'm using is to have the py-impactjs repo in my home directory and on my run path, and then my games exist in my projects directory as individual git repos.  I use symlinks to setup the linkage from so that the listing in py-impactjs can see the games.  That way, the source control never includes impact specific stuff.  py-impactjs can be run from anywhere in the filesys and still find the games.

**Comment by joeyespo** [comment]
Excellent!

Yeah, one of the goals of this project was to solve it in a cross-platform way. Unfortunately symlinks won't work on Windows, which is why I had this project glue it all together instead of going down that road.

I'll take a look!

**Comment by DeaconDesperado** [comment]
That thought had occurred to me.  The symlinks was merely the way I adjusted things for my own workflow.

I like how easy it is to get up and running currently, but maybe there is some merit to setting up a lightweight, optional configuration that would allow filepaths to determine where potential games live.  The new game functionality from #4 could append to this config, but it would also be simple enough that the user could have their games live anywhere on their filesystem and the api calls for each game would adjust accordingly. 

I realize this adds a little more bulk but I'm curious how you feel about it.
